version: '3.0'
services:
    r1:
        build:
            context: ./redis-dynomite
            dockerfile: Dockerfile
        restart: always
        image: "redis/dynomite:0.0.1"
        networks:
            app_net:
                ipv4_address: 172.48.0.2
        container_name: r1
        command: /start/start1.sh
    r2:
        build:
            context: ./redis-dynomite
            dockerfile: Dockerfile
        restart: always
        image: "redis/dynomite:0.0.1"
        networks:
            app_net:
                ipv4_address: 172.48.0.3
        container_name: r2
        command: /start/start2.sh
    r3:
        build:
            context: ./redis-dynomite
            dockerfile: Dockerfile
        restart: always
        image: "redis/dynomite:0.0.1"
        networks:
            app_net:
                ipv4_address: 172.48.0.4
        container_name: r3
        command: /start/start3.sh

networks:
    app_net:
        driver: bridge
        ipam:
            driver: default
            config:
            -
              subnet: 172.48.0.0/24
